# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
   echo " Downloading latest mxpc pipeline image"
   docker pull mxpc-pipeline-tools-cli:0.0.4 
  displayName: "Downloading latest mxpc pipeline image"

- script: |
    echo Executing mxpc-pipeline-tools-cli
    docker run -it private-cloud.registry.mendix.com/mxpc-pipeline-tools-cli:0.0.4 ./mxpc-pipeline-tools-cli
  displayName: 'Executing mxpc-pipeline-tools-cli to create MendixApp'
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'